// AUTO-GENERATED from data/rules.yaml — the default matching-rule set seeded into
// the DB on first boot (both Pi embedded libSQL and serverless Turso). The live
// rules are edited via the admin UI (DB-backed); change this file to change the
// seed. See docs/adr/0002 and #188.
export default [
  {
    id: 'enrich_lesb_woman',
    rule_type: 'enrichment',
    trigger_attribute: 'orientation',
    trigger_value: 'lesbian',
    context_attribute: null,
    context_value: null,
    target_attribute: 'gender',
    target_value: 'woman',
  },
  {
    id: 'enrich_gay_lesb',
    rule_type: 'enrichment',
    trigger_attribute: 'orientation',
    trigger_value: 'gay',
    context_attribute: 'gender',
    context_value: 'woman',
    target_attribute: 'orientation',
    target_value: 'lesbian',
  },
  {
    id: 'enrich_homo_lesb',
    rule_type: 'enrichment',
    trigger_attribute: 'orientation',
    trigger_value: 'homosexual',
    context_attribute: 'gender',
    context_value: 'woman',
    target_attribute: 'orientation',
    target_value: 'lesbian',
  },
  {
    id: 'acc_pan',
    rule_type: 'acceptance',
    trigger_attribute: 'orientation',
    trigger_value: 'pan',
    context_attribute: null,
    context_value: null,
    target_attribute: 'gender',
    target_value: 'man, woman, nonbinary, cis-man, cis-woman, trans-man, trans-woman, men, women',
  },
  {
    id: 'acc_queer',
    rule_type: 'acceptance',
    trigger_attribute: 'orientation',
    trigger_value: 'queer',
    context_attribute: null,
    context_value: null,
    target_attribute: 'gender',
    target_value: 'man, woman, nonbinary, cis-man, cis-woman, trans-man, trans-woman, men, women',
  },
  {
    id: 'acc_bi',
    rule_type: 'acceptance',
    trigger_attribute: 'orientation',
    trigger_value: 'bi',
    context_attribute: null,
    context_value: null,
    target_attribute: 'gender',
    target_value: 'man, woman, cis-man, cis-woman, men, women',
  },
  {
    id: 'acc_bisexual',
    rule_type: 'acceptance',
    trigger_attribute: 'orientation',
    trigger_value: 'bisexual',
    context_attribute: null,
    context_value: null,
    target_attribute: 'gender',
    target_value: 'man, woman, cis-man, cis-woman, men, women',
  },
  {
    id: 'acc_lesb',
    rule_type: 'acceptance',
    trigger_attribute: 'orientation',
    trigger_value: 'lesbian',
    context_attribute: null,
    context_value: null,
    target_attribute: 'gender',
    target_value: 'woman, cis-woman, women',
  },
  {
    id: 'acc_gay_man',
    rule_type: 'acceptance',
    trigger_attribute: 'orientation',
    trigger_value: 'gay',
    context_attribute: null,
    context_value: null,
    target_attribute: 'gender',
    target_value: 'man, cis-man, men',
  },
  {
    id: 'acc_homo_man',
    rule_type: 'acceptance',
    trigger_attribute: 'orientation',
    trigger_value: 'homosexual',
    context_attribute: null,
    context_value: null,
    target_attribute: 'gender',
    target_value: 'man, cis-man, men',
  },
  {
    id: 'acc_gay_woman',
    rule_type: 'acceptance',
    trigger_attribute: 'orientation',
    trigger_value: 'gay',
    context_attribute: 'gender',
    context_value: 'woman',
    target_attribute: 'gender',
    target_value: 'woman, cis-woman, women',
  },
  {
    id: 'acc_homo_woman',
    rule_type: 'acceptance',
    trigger_attribute: 'orientation',
    trigger_value: 'homosexual',
    context_attribute: 'gender',
    context_value: 'woman',
    target_attribute: 'gender',
    target_value: 'woman, cis-woman, women',
  },
  {
    id: 'acc_str_man',
    rule_type: 'acceptance',
    trigger_attribute: 'orientation',
    trigger_value: 'straight',
    context_attribute: 'gender',
    context_value: 'man',
    target_attribute: 'gender',
    target_value: 'woman, cis-woman, women',
  },
  {
    id: 'acc_str_woman',
    rule_type: 'acceptance',
    trigger_attribute: 'orientation',
    trigger_value: 'straight',
    context_attribute: 'gender',
    context_value: 'woman',
    target_attribute: 'gender',
    target_value: 'man, cis-man, men',
  },
  {
    id: 'exp_woman',
    rule_type: 'expansion',
    trigger_attribute: 'gender',
    trigger_value: 'woman',
    context_attribute: null,
    context_value: null,
    target_attribute: 'gender',
    target_value: 'woman, cis-woman, trans-woman, female, women',
  },
  {
    id: 'exp_female',
    rule_type: 'expansion',
    trigger_attribute: 'gender',
    trigger_value: 'female',
    context_attribute: null,
    context_value: null,
    target_attribute: 'gender',
    target_value: 'woman, cis-woman, trans-woman, female, women',
  },
  {
    id: 'exp_women',
    rule_type: 'expansion',
    trigger_attribute: 'gender',
    trigger_value: 'women',
    context_attribute: null,
    context_value: null,
    target_attribute: 'gender',
    target_value: 'woman, cis-woman, trans-woman, female, women',
  },
  {
    id: 'exp_trans_woman',
    rule_type: 'expansion',
    trigger_attribute: 'gender',
    trigger_value: 'trans-woman',
    context_attribute: null,
    context_value: null,
    target_attribute: 'gender',
    target_value: 'woman, cis-woman, trans-woman, female, women',
  },
  {
    id: 'exp_cis_woman',
    rule_type: 'expansion',
    trigger_attribute: 'gender',
    trigger_value: 'cis-woman',
    context_attribute: null,
    context_value: null,
    target_attribute: 'gender',
    target_value: 'woman, cis-woman, trans-woman, female, women',
  },
  {
    id: 'exp_man',
    rule_type: 'expansion',
    trigger_attribute: 'gender',
    trigger_value: 'man',
    context_attribute: null,
    context_value: null,
    target_attribute: 'gender',
    target_value: 'man, cis-man, trans-man, male, men',
  },
  {
    id: 'exp_male',
    rule_type: 'expansion',
    trigger_attribute: 'gender',
    trigger_value: 'male',
    context_attribute: null,
    context_value: null,
    target_attribute: 'gender',
    target_value: 'man, cis-man, trans-man, male, men',
  },
  {
    id: 'exp_men',
    rule_type: 'expansion',
    trigger_attribute: 'gender',
    trigger_value: 'men',
    context_attribute: null,
    context_value: null,
    target_attribute: 'gender',
    target_value: 'man, cis-man, trans-man, male, men',
  },
  {
    id: 'exp_trans_man',
    rule_type: 'expansion',
    trigger_attribute: 'gender',
    trigger_value: 'trans-man',
    context_attribute: null,
    context_value: null,
    target_attribute: 'gender',
    target_value: 'man, cis-man, trans-man, male, men',
  },
  {
    id: 'exp_cis_man',
    rule_type: 'expansion',
    trigger_attribute: 'gender',
    trigger_value: 'cis-man',
    context_attribute: null,
    context_value: null,
    target_attribute: 'gender',
    target_value: 'man, cis-man, trans-man, male, men',
  },
  {
    id: 'exp_nonbinary',
    rule_type: 'expansion',
    trigger_attribute: 'gender',
    trigger_value: 'nonbinary',
    context_attribute: null,
    context_value: null,
    target_attribute: 'gender',
    target_value:
      'nonbinary, enby, non-binary, genderqueer, agender, trans-nonbinary, cis-nonbinary',
  },
  {
    id: 'exp_enby',
    rule_type: 'expansion',
    trigger_attribute: 'gender',
    trigger_value: 'enby',
    context_attribute: null,
    context_value: null,
    target_attribute: 'gender',
    target_value:
      'nonbinary, enby, non-binary, genderqueer, agender, trans-nonbinary, cis-nonbinary',
  },
  {
    id: 'exp_non_binary',
    rule_type: 'expansion',
    trigger_attribute: 'gender',
    trigger_value: 'non-binary',
    context_attribute: null,
    context_value: null,
    target_attribute: 'gender',
    target_value:
      'nonbinary, enby, non-binary, genderqueer, agender, trans-nonbinary, cis-nonbinary',
  },
  {
    id: 'exp_genderqueer',
    rule_type: 'expansion',
    trigger_attribute: 'gender',
    trigger_value: 'genderqueer',
    context_attribute: null,
    context_value: null,
    target_attribute: 'gender',
    target_value:
      'nonbinary, enby, non-binary, genderqueer, agender, trans-nonbinary, cis-nonbinary',
  },
  {
    id: 'exp_agender',
    rule_type: 'expansion',
    trigger_attribute: 'gender',
    trigger_value: 'agender',
    context_attribute: null,
    context_value: null,
    target_attribute: 'gender',
    target_value:
      'nonbinary, enby, non-binary, genderqueer, agender, trans-nonbinary, cis-nonbinary',
  },
];
