// The default matching-rule set, seeded into the DB on first boot (both the Pi's
// embedded libSQL and serverless Turso). This is the single source of truth for
// the defaults and is bundled into the Lambda by esbuild (a YAML data file would
// not be). Live rules are edited via the admin UI (DB-backed). See ADR 0002 / #188.
//
// Each row is a tuple of [id, rule_type, trigger_attribute, trigger_value, context_attribute, context_value, target_attribute, target_value].

const FIELDS = [
  'id',
  'rule_type',
  'trigger_attribute',
  'trigger_value',
  'context_attribute',
  'context_value',
  'target_attribute',
  'target_value',
];

const rows = [
  ['enrich_lesb_woman', 'enrichment', 'orientation', 'lesbian', null, null, 'gender', 'woman'],
  [
    'enrich_gay_lesb',
    'enrichment',
    'orientation',
    'gay',
    'gender',
    'woman',
    'orientation',
    'lesbian',
  ],
  [
    'enrich_homo_lesb',
    'enrichment',
    'orientation',
    'homosexual',
    'gender',
    'woman',
    'orientation',
    'lesbian',
  ],
  [
    'acc_pan',
    'acceptance',
    'orientation',
    'pan',
    null,
    null,
    'gender',
    'man, woman, nonbinary, cis-man, cis-woman, trans-man, trans-woman, men, women',
  ],
  [
    'acc_queer',
    'acceptance',
    'orientation',
    'queer',
    null,
    null,
    'gender',
    'man, woman, nonbinary, cis-man, cis-woman, trans-man, trans-woman, men, women',
  ],
  [
    'acc_bi',
    'acceptance',
    'orientation',
    'bi',
    null,
    null,
    'gender',
    'man, woman, cis-man, cis-woman, men, women',
  ],
  [
    'acc_bisexual',
    'acceptance',
    'orientation',
    'bisexual',
    null,
    null,
    'gender',
    'man, woman, cis-man, cis-woman, men, women',
  ],
  [
    'acc_lesb',
    'acceptance',
    'orientation',
    'lesbian',
    null,
    null,
    'gender',
    'woman, cis-woman, women',
  ],
  ['acc_gay_man', 'acceptance', 'orientation', 'gay', null, null, 'gender', 'man, cis-man, men'],
  [
    'acc_homo_man',
    'acceptance',
    'orientation',
    'homosexual',
    null,
    null,
    'gender',
    'man, cis-man, men',
  ],
  [
    'acc_gay_woman',
    'acceptance',
    'orientation',
    'gay',
    'gender',
    'woman',
    'gender',
    'woman, cis-woman, women',
  ],
  [
    'acc_homo_woman',
    'acceptance',
    'orientation',
    'homosexual',
    'gender',
    'woman',
    'gender',
    'woman, cis-woman, women',
  ],
  [
    'acc_str_man',
    'acceptance',
    'orientation',
    'straight',
    'gender',
    'man',
    'gender',
    'woman, cis-woman, women',
  ],
  [
    'acc_str_woman',
    'acceptance',
    'orientation',
    'straight',
    'gender',
    'woman',
    'gender',
    'man, cis-man, men',
  ],
  [
    'exp_woman',
    'expansion',
    'gender',
    'woman',
    null,
    null,
    'gender',
    'woman, cis-woman, trans-woman, female, women',
  ],
  [
    'exp_female',
    'expansion',
    'gender',
    'female',
    null,
    null,
    'gender',
    'woman, cis-woman, trans-woman, female, women',
  ],
  [
    'exp_women',
    'expansion',
    'gender',
    'women',
    null,
    null,
    'gender',
    'woman, cis-woman, trans-woman, female, women',
  ],
  [
    'exp_trans_woman',
    'expansion',
    'gender',
    'trans-woman',
    null,
    null,
    'gender',
    'woman, cis-woman, trans-woman, female, women',
  ],
  [
    'exp_cis_woman',
    'expansion',
    'gender',
    'cis-woman',
    null,
    null,
    'gender',
    'woman, cis-woman, trans-woman, female, women',
  ],
  [
    'exp_man',
    'expansion',
    'gender',
    'man',
    null,
    null,
    'gender',
    'man, cis-man, trans-man, male, men',
  ],
  [
    'exp_male',
    'expansion',
    'gender',
    'male',
    null,
    null,
    'gender',
    'man, cis-man, trans-man, male, men',
  ],
  [
    'exp_men',
    'expansion',
    'gender',
    'men',
    null,
    null,
    'gender',
    'man, cis-man, trans-man, male, men',
  ],
  [
    'exp_trans_man',
    'expansion',
    'gender',
    'trans-man',
    null,
    null,
    'gender',
    'man, cis-man, trans-man, male, men',
  ],
  [
    'exp_cis_man',
    'expansion',
    'gender',
    'cis-man',
    null,
    null,
    'gender',
    'man, cis-man, trans-man, male, men',
  ],
  [
    'exp_nonbinary',
    'expansion',
    'gender',
    'nonbinary',
    null,
    null,
    'gender',
    'nonbinary, enby, non-binary, genderqueer, agender, trans-nonbinary, cis-nonbinary',
  ],
  [
    'exp_enby',
    'expansion',
    'gender',
    'enby',
    null,
    null,
    'gender',
    'nonbinary, enby, non-binary, genderqueer, agender, trans-nonbinary, cis-nonbinary',
  ],
  [
    'exp_non_binary',
    'expansion',
    'gender',
    'non-binary',
    null,
    null,
    'gender',
    'nonbinary, enby, non-binary, genderqueer, agender, trans-nonbinary, cis-nonbinary',
  ],
  [
    'exp_genderqueer',
    'expansion',
    'gender',
    'genderqueer',
    null,
    null,
    'gender',
    'nonbinary, enby, non-binary, genderqueer, agender, trans-nonbinary, cis-nonbinary',
  ],
  [
    'exp_agender',
    'expansion',
    'gender',
    'agender',
    null,
    null,
    'gender',
    'nonbinary, enby, non-binary, genderqueer, agender, trans-nonbinary, cis-nonbinary',
  ],
  // Role rules (see docs/MATCHING_RULES.md). Cross-match makes complementary roles
  // find each other bidirectionally; expansion broadens a role to its sub-kinds so
  // a "handler" wish also reaches a "pup"/"kitten" without enumerating every pair.
  ['exp_pet', 'expansion', 'role', 'pet', null, null, 'role', 'pet, pup, kitten'],
  ['cross_handler_pet', 'cross_match', 'role', 'handler', null, null, 'role', 'pet'],
  ['cross_top_bottom', 'cross_match', 'role', 'top', null, null, 'role', 'bottom'],
];

export default rows.map((row) => Object.fromEntries(FIELDS.map((f, i) => [f, row[i]])));
