// The default matching-rule set, seeded into the DB on first boot (both the Pi's
// embedded libSQL and serverless Turso). This is the single source of truth for
// the defaults and is bundled into the Lambda by esbuild (a YAML data file would
// not be). Live rules are edited via the admin UI (DB-backed). See ADR 0002 / #188.
//
// Each row is a tuple of [id, rule_type, trigger_attribute, trigger_value, context_attribute, context_value, target_attribute, target_value].

const FIELDS = [
  'id',
  'rule_type',
  'trigger_attribute',
  'trigger_value',
  'context_attribute',
  'context_value',
  'target_attribute',
  'target_value',
];

const rows = [
  ['enrich_lesb_woman', 'enrichment', 'orientation', 'lesbian', null, null, 'gender', 'woman'],
  [
    'enrich_gay_lesbian',
    'enrichment',
    'orientation',
    'gay',
    'gender',
    'woman',
    'orientation',
    'lesbian',
  ],
  [
    'enrich_homosexual_lesbian',
    'enrichment',
    'orientation',
    'homosexual',
    'gender',
    'woman',
    'orientation',
    'lesbian',
  ],
  [
    'acc_pan',
    'acceptance',
    'orientation',
    'pan',
    null,
    null,
    'gender',
    'man, woman, nonbinary, cis-man, cis-woman, trans-man, trans-woman, men, women',
  ],
  [
    'acc_queer',
    'acceptance',
    'orientation',
    'queer',
    null,
    null,
    'gender',
    'man, woman, nonbinary, cis-man, cis-woman, trans-man, trans-woman, men, women',
  ],
  [
    'acc_bi',
    'acceptance',
    'orientation',
    'bi',
    null,
    null,
    'gender',
    'man, woman, cis-man, cis-woman, men, women',
  ],
  [
    'acc_bisexual',
    'acceptance',
    'orientation',
    'bisexual',
    null,
    null,
    'gender',
    'man, woman, cis-man, cis-woman, men, women',
  ],
  [
    'acc_lesbian',
    'acceptance',
    'orientation',
    'lesbian',
    null,
    null,
    'gender',
    'woman, cis-woman, women',
  ],
  ['acc_gay_man', 'acceptance', 'orientation', 'gay', null, null, 'gender', 'man, cis-man, men'],
  [
    'acc_homosexual_man',
    'acceptance',
    'orientation',
    'homosexual',
    null,
    null,
    'gender',
    'man, cis-man, men',
  ],
  [
    'acc_gay_woman',
    'acceptance',
    'orientation',
    'gay',
    'gender',
    'woman',
    'gender',
    'woman, cis-woman, women',
  ],
  [
    'acc_homosexual_woman',
    'acceptance',
    'orientation',
    'homosexual',
    'gender',
    'woman',
    'gender',
    'woman, cis-woman, women',
  ],
  [
    'acc_str_man',
    'acceptance',
    'orientation',
    'straight',
    'gender',
    'man',
    'gender',
    'woman, cis-woman, women',
  ],
  [
    'acc_str_woman',
    'acceptance',
    'orientation',
    'straight',
    'gender',
    'woman',
    'gender',
    'man, cis-man, men',
  ],
  [
    'exp_woman',
    'expansion',
    'gender',
    'woman',
    null,
    null,
    'gender',
    'woman, cis-woman, trans-woman, female, women',
  ],
  [
    'exp_female',
    'expansion',
    'gender',
    'female',
    null,
    null,
    'gender',
    'woman, cis-woman, trans-woman, female, women',
  ],
  [
    'exp_women',
    'expansion',
    'gender',
    'women',
    null,
    null,
    'gender',
    'woman, cis-woman, trans-woman, female, women',
  ],
  [
    'exp_trans_woman',
    'expansion',
    'gender',
    'trans-woman',
    null,
    null,
    'gender',
    'woman, cis-woman, trans-woman, female, women',
  ],
  [
    'exp_cis_woman',
    'expansion',
    'gender',
    'cis-woman',
    null,
    null,
    'gender',
    'woman, cis-woman, trans-woman, female, women',
  ],
  [
    'exp_man',
    'expansion',
    'gender',
    'man',
    null,
    null,
    'gender',
    'man, cis-man, trans-man, male, men',
  ],
  [
    'exp_male',
    'expansion',
    'gender',
    'male',
    null,
    null,
    'gender',
    'man, cis-man, trans-man, male, men',
  ],
  [
    'exp_men',
    'expansion',
    'gender',
    'men',
    null,
    null,
    'gender',
    'man, cis-man, trans-man, male, men',
  ],
  [
    'exp_trans_man',
    'expansion',
    'gender',
    'trans-man',
    null,
    null,
    'gender',
    'man, cis-man, trans-man, male, men',
  ],
  [
    'exp_cis_man',
    'expansion',
    'gender',
    'cis-man',
    null,
    null,
    'gender',
    'man, cis-man, trans-man, male, men',
  ],
  [
    'exp_nonbinary',
    'expansion',
    'gender',
    'nonbinary',
    null,
    null,
    'gender',
    'nonbinary, enby, non-binary, genderqueer, agender, trans-nonbinary, cis-nonbinary',
  ],
  [
    'exp_enby',
    'expansion',
    'gender',
    'enby',
    null,
    null,
    'gender',
    'nonbinary, enby, non-binary, genderqueer, agender, trans-nonbinary, cis-nonbinary',
  ],
  [
    'exp_non_binary',
    'expansion',
    'gender',
    'non-binary',
    null,
    null,
    'gender',
    'nonbinary, enby, non-binary, genderqueer, agender, trans-nonbinary, cis-nonbinary',
  ],
  [
    'exp_genderqueer',
    'expansion',
    'gender',
    'genderqueer',
    null,
    null,
    'gender',
    'nonbinary, enby, non-binary, genderqueer, agender, trans-nonbinary, cis-nonbinary',
  ],
  [
    'exp_agender',
    'expansion',
    'gender',
    'agender',
    null,
    null,
    'gender',
    'nonbinary, enby, non-binary, genderqueer, agender, trans-nonbinary, cis-nonbinary',
  ],
  // Role rules (see docs/MATCHING_RULES.md). Cross-match makes complementary roles
  // find each other bidirectionally; expansion broadens a role to its sub-kinds so
  // a "handler" wish also reaches a "pup"/"kitten" without enumerating every pair.
  //
  // Note: expansion rules are single-pass (not recursive), so synonym redirects
  // (e.g. sub → submissive) must repeat the full target list — this is intentional
  // data redundancy, not a code smell. See #232 for context-gated expansion work.

  // Pet/handler
  [
    'exp_role_pet',
    'expansion',
    'role',
    'pet',
    null,
    null,
    'role',
    'pet, pup, puppy, kitten, kitty, pony',
  ],
  ['cross_handler_pet', 'cross_match', 'role', 'handler', null, null, 'role', 'pet'],

  // Top/bottom and switch
  ['cross_top_bottom', 'cross_match', 'role', 'top', null, null, 'role', 'bottom'],
  ['cross_switch_top', 'cross_match', 'role', 'switch', null, null, 'role', 'top'],
  ['cross_switch_bottom', 'cross_match', 'role', 'switch', null, null, 'role', 'bottom'],

  // D/s (dominant / submissive) — note: expansion rules are flat so sub and dom
  // each carry their own full synonym list
  [
    'cross_dominant_submissive',
    'cross_match',
    'role',
    'dominant',
    null,
    null,
    'role',
    'submissive',
  ],
  [
    'exp_role_submissive',
    'expansion',
    'role',
    'submissive',
    null,
    null,
    'role',
    'submissive, sub, slave, service-sub, little',
  ],
  [
    'exp_role_sub',
    'expansion',
    'role',
    'sub',
    null,
    null,
    'role',
    'submissive, sub, slave, service-sub, little',
  ],
  [
    'exp_role_dominant',
    'expansion',
    'role',
    'dominant',
    null,
    null,
    'role',
    'dominant, dom, domme, master, mistress',
  ],
  [
    'exp_role_dom',
    'expansion',
    'role',
    'dom',
    null,
    null,
    'role',
    'dominant, dom, domme, master, mistress',
  ],
  [
    'exp_role_domme',
    'expansion',
    'role',
    'domme',
    null,
    null,
    'role',
    'dominant, dom, domme, master, mistress',
  ],

  // M/s (master / slave)
  ['cross_master_slave', 'cross_match', 'role', 'master', null, null, 'role', 'slave'],

  // Owner / property
  ['cross_owner_property', 'cross_match', 'role', 'owner', null, null, 'role', 'property'],

  // Rope bondage (rigger / rope-bunny)
  ['cross_rigger_rope_bunny', 'cross_match', 'role', 'rigger', null, null, 'role', 'rope-bunny'],

  // Sadist / masochist
  ['cross_sadist_masochist', 'cross_match', 'role', 'sadist', null, null, 'role', 'masochist'],

  // Caregiver / little (age-play adjacent; consensual adult dynamic)
  ['cross_caregiver_little', 'cross_match', 'role', 'caregiver', null, null, 'role', 'little'],
  [
    'exp_role_caregiver',
    'expansion',
    'role',
    'caregiver',
    null,
    null,
    'role',
    'caregiver, daddy, mommy, mummy',
  ],

  // Brat-tamer / brat
  ['cross_brat_tamer_brat', 'cross_match', 'role', 'brat-tamer', null, null, 'role', 'brat'],

  // Vers / versatile (queer sexual & BDSM versatile — synonym pair)
  ['exp_role_vers', 'expansion', 'role', 'vers', null, null, 'role', 'vers, versatile'],
  ['exp_role_versatile', 'expansion', 'role', 'versatile', null, null, 'role', 'vers, versatile'],

  // Write-time exclusion/contradiction rules (mutually exclusive pairings)
  ['excl_gay_straight', 'exclusion', 'orientation', 'gay', null, null, 'orientation', 'straight'],
  ['excl_lesbian_man', 'exclusion', 'orientation', 'lesbian', 'gender', 'man', 'gender', 'man'],
];

export default rows.map((row) => Object.fromEntries(FIELDS.map((f, i) => [f, row[i]])));
