services:
  wishboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wishboard
    ports:
      - "3000:3000"
    volumes:
      - wishboard_data:/app/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # - WISHBOARD_ADMIN_USERNAME=admin
      # - WISHBOARD_ADMIN_SECRET=admin-board
      # - CORS_ALLOWED_ORIGINS=http://your-domain.com

volumes:
  wishboard_data:
